### ISSUE TITLE
OTA Updates: No Download Speed 

### ISSUE THREAD

**Issue by chsims1** [volumio/volumio3-backend#34]
Trivial, but looks bad that simple bugs aren't corrected, especially in launch of Volumio3.

![volumio](https://user-images.githubusercontent.com/6384195/141675643-b4d26022-ba52-470e-a0db-98c2188268d3.png)

Can we also have the units too please. ;)

**Comment by chsims1** [comment]
Still here January 2022.  I understand that there are priorities, but so simple a bug would surely take a few minutes to correct.  If not, this is why the number of issues just keeps on creeping up.

**Comment by volumio** [comment]
Solution is not easy on buster. We can remove the speed indication in the meantime
