### ISSUE TITLE
Command line interface dows not work, wrong node path

### ISSUE THREAD

**Issue by pbando** [volumio/volumio3-backend#51]
Command line interface does not work:

volumio@volumio3:~$ /volumio/app/plugins/system_controller/volumio_command_line_client/commands/playback.js 
-bash: /volumio/app/plugins/system_controller/volumio_command_line_client/commands/playback.js: /bin/node: bad interpreter: No such file or directory

volumio@volumio3:~$ whereis node
node: /usr/bin/node /usr/include/node

Ananysis:
Wrong node path in script js files: #!/bin/node  
Instead, it should be:   #!/usr/bin/node

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/volumio3-backend/commit/1f51ed61b959a7bfe3aabfc38f566549a6f48929
