### ISSUE TITLE
Software update wiped out all existing settings without warning.

### ISSUE THREAD

**Issue by teq0** [volumio/volumio3-backend#56]
I haven't updated in a while, I didn't actually check the existing version before I did the update, but doing a software update from in Settings/System just completely wiped out all of my settings and favourites.

I would have preferred to stay on the old version, I had a lot of favourites and a lot of web radio settings that I had to enter manually that I've now lost. Extremely poor user experience. If there had been a warning I could have at least ssh'd in and taken a copy.

**Comment by teq0** [comment]
As far as I can tell from the forums this is "as designed." I did not see any warning that my settings would be wiped out, or maybe I did but it didn't register because I have never seen another piece of software in my entire life that erases everything as part of a normal "update" and forces you to create an online account just to reinstall the things you've been using for years. This is about as amateur and user-unfriendly as it gets.

**Comment by volumio** [comment]
This is the message that gets shown before you click on Update:

---------------------------
This will upgrade your system to Volumio 3, the latest and greatest Volumio experience.


IMPORTANT WHEN UPGRADING FROM VOLUMIO 2! To ensure a smooth transition, this device will be factory reset. All data including installed plugins, (wifi) settings, and the music library will be lost.

If your device only has a wifi connection, please connect to the Volumio-XXXXXX hotspot or ethernet to setup your device and connect to your wifi network.

For any issue, you can contact our support at....

The whole Volumio team wish you great listening sessions with Volumio 3.
-------------------

If that was not clear to you, let us know how we could have improved the message to make it more clear.

**Comment by teq0** [comment]
I've been using Volumio for many years, and I even made a contribution to the code, I've upgraded it many times, I hardly ever bother to read the message because it's usually just the change log, and I'm sure many other people won't either.

If you want to make it clearer I would put a huge

### WARNING! READ BEFORE PROCEEDING! THIS "UPDATE" IS EQUIVALENT TO A FRESH INSTALLATION, ALL EXISTING SETTINGS AND PLUGINS WILL BE LOST.

at the top.

But honestly, if it were me, and there were changes in the format of configs files or whatever, I would have put in another couple of weeks of effort to automate the transforms, not just wipe out people's installations.
