### ISSUE TITLE
ChipDip DAC for Volumio 3

### ISSUE THREAD

**Issue by chipdipru** [volumio/volumio3-backend#61]
The kernel driver already present in the Kernel. Please add a line to the  dacs.json file
`{"id":"chipdip-master-dac","name":"ChipDip DAC","overlay":"chipdip-dac","alsanum":"2","alsacard":"ChipDipDAC","mixer":"","modules":"","script":"","needsreboot":"yes"},`

**Comment by volumio** [comment]
Unfortunately we might have to revert the latest kernel, due to some incompatibilities.

Do you know from which kernel version is this module included?

Also, please send directly a Pull Request for the inclusion in the JSON. See:
https://developers.volumio.com/I2S%20DACs

Thanks

**Comment by chipdipru** [comment]
2021.07.27 version  5.10.52+
 
https://github.com/Hexxeh/rpi-firmware/commit/b986fda889737f6ce0a4acda89d447f78d0a1a73#diff-fdf06e19cdcd4c62062c1c78f0c986585eafedb4e864d95a347c2f7f5f1bfdf1
