### ISSUE TITLE
Spotify Connect doesn't change the cover when start playing

### ISSUE THREAD

**Issue by schmurtzm** [volumio/volumio3-backend#64]
**issue :** 
When you start a new Spotify Connect session on Volumio the cover is not actualized.

**Steps to reproduce :** 

1. start to play a Spotify Connect song on Volumio
2. switch spotify connect to another player
3. change the song
4. switch back Spotify Connect to Volumio

Result :  Volumio stay on the firt cover.

Ps: not totally sure to post this issue on the right repo, not easy to find the right one for new users :p 

Thank you.

**Comment by ashthespy** [comment]
>Ps: not totally sure to post this issue on the right repo, not easy to find the right one for new users :p

Plugins are at [volumio/volumio-plugins-sources](https://github.com/volumio/volumio-plugins-sources) and more commonly users post at [community.volumio.org](https://community.volumio.org/)
