### ISSUE TITLE
executeRestEndpoint() invariably rejects

### ISSUE THREAD

**Issue by patrickkfkan** [volumio/volumio3-backend#71]
Commit c6f78bd0166638805e7d8aada977b15ed469753d with the addition of lines 210 and 211 means that `executeRestEndpoint()` will always reject, even if the endpoint exists and is executed. Furthermore, if the endpoint is executed successfully, the `defer` resolves *after* the reject and this causes an exception to be thrown.

**Comment by volumio** [comment]
Thanks! Fixed with https://github.com/volumio/volumio3-backend/commit/a28aaa9f2481a95b16707860e2ee7bc25cd8670b
